-- OPH65 V2.14 - Initialisation Supabase
-- À exécuter UNE SEULE FOIS dans Supabase > SQL Editor > New query > Run.

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.logements (
  lot_no text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.suivi_logements (
  lot_no text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.app_files (
  key text primary key,
  filename text not null,
  content_b64 text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.bc_validations (
  token text primary key,
  bc_no text not null,
  lot_no text not null,
  work_category text not null,
  company_email text,
  status text not null default 'pending' check (status in ('pending','validated')),
  created_at timestamptz not null default now(),
  validated_at timestamptz
);

create table if not exists public.mail_history (
  id bigint generated by default as identity primary key,
  kind text not null,
  recipient text,
  subject text,
  lot_no text,
  bc_no text,
  work_category text,
  sent_at timestamptz not null default now()
);

create index if not exists idx_bc_validations_lot on public.bc_validations(lot_no);
create index if not exists idx_bc_validations_bc on public.bc_validations(bc_no);
create index if not exists idx_mail_history_bc on public.mail_history(bc_no);

-- RLS activé : aucune donnée n'est directement accessible avec la clé publique anon.
-- L'application Streamlit utilise exclusivement la clé service_role côté serveur.
alter table public.app_settings enable row level security;
alter table public.logements enable row level security;
alter table public.suivi_logements enable row level security;
alter table public.app_files enable row level security;
alter table public.bc_validations enable row level security;
alter table public.mail_history enable row level security;

-- Droits explicites pour le rôle serveur utilisé par la Secret key.
grant all on table public.app_settings to service_role;
grant all on table public.logements to service_role;
grant all on table public.suivi_logements to service_role;
grant all on table public.app_files to service_role;
grant all on table public.bc_validations to service_role;
grant all on table public.mail_history to service_role;
grant usage, select on all sequences in schema public to service_role;
